### ISSUE TITLE
Can not run Your Demo?

### ISSUE THREAD

**Issue by logicred** [QualityAssessment/DOVER#2]
Thank you for your code implemention. However, the demo gets stuck after creating a new conda environment and following your guidelines in the README.md, with the output:

divided
UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
None False
Setting backbone: technical_backbone
divided
Using Imagenet 22K pretrain False
Setting backbone: aesthetic_backbone
True
Setting head: technical_head
Setting head: aesthetic_head
(Stuck!)

I am looking forward to your reply and thanks again.

**Comment by teowu** [comment]
Hi can you show me your full command? Which .py are you using?

I guess the error might be due to the path of the input data.
I have also fell in similar error when the data cannot be read properly.

**Comment by logicred** [comment]
Simplely using:
python evaluate_one_video.py -v ./demo/17734.mp4

**Comment by teowu** [comment]
This is strange…we chance checked this on multiple machines.
Maybe you can share me your hardware and CUDA versions and we may further seek ways to help you.

**Comment by liulizhou** [comment]
I also stuck: 
Setting head: technical_head
Setting head: aesthetic_head
(Stuck!)
Then debug:
```
evaluator = DOVER(**opt["model"]["args"]).to(args.device)
```
The model can be loaded normally, but cannot be moved to Cuda.
My device:
nvidia A10, Cuda 11.6

**Comment by teowu** [comment]
Hi, can you print the `args.device`? Or, maybe you can change the `.to(args.device)` all to `.cuda()` and see whether it works.

Looking forward to your reply.

**Comment by teowu** [comment]
I noticed that it might wait a bit for my V100 to fully load the model, but at most one minute.

**Comment by teowu** [comment]
We tried on NVIDIA A40 and it is also fine. Perhaps there are some errors related to your environment?

**Comment by liulizhou** [comment]
I print(args.device), the. result is:
`cuda`
I also tried both `to(args.cuda)` and `.cuda()`, both stuck.
My pytorch version:
```
1.12.1+cu116
```

**Comment by teowu** [comment]
This is strange. In my environments (python 3.8/3.9) they are fine, but not okay with python 3.10.

**Comment by teowu** [comment]
We will try to solve this! Meanwhile if you find some solutions please feel free to submit a pull request!

**Comment by liulizhou** [comment]
> oth `to(args.device)` a



> We will try to solve this! Meanwhile if you find some solutions please feel free to submit a pull request!


> 

Ok, I am still debugging, I will synchronize it in time if I find the problem.
My python version:`python 3.8`

**Comment by liulizhou** [comment]
> 



> Thank you so much. It is strange why it does not work here...my new Python 3.8 environment is okay with it.

Hello, 
I found the reason. 
`import torch` must be at the first line.
The file evaluate_one_video.py: 
```
import argparse
import pickle as pkl
import decord
import numpy as np
import torch
import yaml
```
change it to:
```
import torch
import argparse
import pickle as pkl
import decord
import numpy as np
import yaml
```
I don't know the specific reason, but I have no problem after putting`import torch` in the first line.
`import torch` of fastvqa  'split_train.py' is on the first line, so there is no problem.

**Comment by teowu** [comment]
Thanks!  We will make the change in our next version!

**Comment by SWHL** [comment]
I've figured out the cause. It's due to the decord library. For details, please see: https://github.com/dmlc/decord/issues/324
