### ISSUE TITLE
Pretrained module is missing 

### ISSUE THREAD

**Issue by Jiahao620** [QualityAssessment/DOVER#3]
This is a wonderful work! 
While the link (https://github.com/QualityAssessment/DOVER/releases/download/v0.1.0/DOVER.pth) you provide seems invalid.
Could you please check it?

**Comment by teowu** [comment]
I clicked this on my smartphone and it seemed downloadable (239.7MB). May I know where the error happens?

**Comment by teowu** [comment]
![D6429C16-202F-4806-BF50-03CB992A586C](https://user-images.githubusercontent.com/38696372/206407262-6c870ea3-b928-45ef-bab1-ffaaacf5e290.png)

**Comment by Jiahao620** [comment]
When I click It, it shows me as following:
![image](https://user-images.githubusercontent.com/92793267/206408134-2f6a6e9e-db10-40c3-8b7b-2bbabd71a1ad.png)
I'm confused with it.

**Comment by teowu** [comment]
CONFUSING…I **logged out** and the link is still downloadable, and here are two ways that may help you now:
1. Try to see the “releases” of the repo. You can get the correct link.
2. Try directly wget this link.

We will also check what error happens here.

**Comment by Jiahao620** [comment]
Thanks a lot! I successfully download pretrained weights! But the file size is slightly different from what you show.
![image](https://user-images.githubusercontent.com/92793267/206411243-782e5855-775b-453e-86fe-e75b8359d62e.png)
