### ISSUE TITLE
missing key split_seed

### ISSUE THREAD

**Issue by zhangxixi0904** [QualityAssessment/DOVER#4]
when running transfer_learning.py, it produce an error:
Traceback (most recent call last):
  File "transfer_learning.py", line 517, in <module>
    main()
  File "transfer_learning.py", line 348, in main
    print(opt["split_seed"])
KeyError: 'split_seed'

Seems that split_seed is missing the default dover.yaml

**Comment by teowu** [comment]
This is solved. Please pull to the newest edition.
We also improved the training code with LVBS and support end-to-end training now.
