### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by AdrienSchadle** [QualityAssessment/DOVER#5]
Hello,

I try to run your demo, but it failed with the following error "torch.cuda.OutOfMemoryError: CUDA out of memory".
Can you help me ?

step to reproduce:
poetry run evaluate_one_video.py -v .\demo\17734.mp4

As you can see I use python 3.10 through poetry.

Next the version of the module imported:
certifi                      2022.12.7
charset-normalizer  2.1.1
colorama                0.4.6
decord                    0.6.0
einops                    0.6.0
filelock                    3.8.2
huggingface-hub    0.11.1
idna                        3.4
numpy                    1.24.0
opencv-python       4.6.0.66
packaging               22.0
pillow                      9.3.0
pyyaml                    6.0
requests                  2.28.1
scipy                       1.9.3
sk-video                  1.1.10
timm                       0.6.12
torch                       1.13.1+cu117 https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-win_amd64.whl 
torchvision              0.14.1+cpu https://download.pytorch.org/whl/cpu/torchvision-0.14.1%2Bcpu-cp310-cp310-win_amd64.whl
tqdm                       4.64.1
typing-extensions    4.4.0
urllib3                      1.26.13

**Comment by teowu** [comment]
Hi Adrien, that might be due to your hardware limitation.
The inference will need around 6GB graphic memory, please make sure your device has enough.
