### ISSUE TITLE
difference results  of the same input video in inference 

### ISSUE THREAD

**Issue by CodingMice** [QualityAssessment/DOVER#6]
I run the command of "python evaluate_one_video.py -f -v demo/17734.mp4", but got first result of "Normalized fused overall score (scale in [0,1]): 0.6913595731824047", second result of "Normalized fused overall score (scale in [0,1]): 0.670431635387203". Is this a correct result?

**Comment by teowu** [comment]
Hi, 

This is correct as DOVER contains a bit randomness. However, as it is also very fast, you may also try to improve the inference stability by running multiple times (e.g. 4-5 repeat runs). The result will be rather stable then.

Best,
Teo

**Comment by hadesfgh** [comment]
hello, what should I do if I want to remove randomness from inference
